- name: Third-Party Risk Assessment
  icon: /assets/images/icon/Third-Party-Risk.png
  description: Securing organisations by providing risk assessments on vendors and supply chain partners, providing insight and meaningful remediation actions.

- name: Penetration Testing
  icon: /assets/images/icon/Pentest.png
  description: Identifying known and unknown vulnerabilities in external and internal environments.

- name: Virtual CISO
  icon: /assets/images/icon/vCISO.png
  description: A tiered offering designed to provide top-tier security experts and their expertise available to all organisations.
